### ISSUE TITLE
SQLote Implementation 

### ISSUE THREAD

**Issue by amanssit** [amanssit/healthyapp#1]

**Comment by manjeshpv** [comment]
https://gist.github.com/manjeshpv/b74bba350e68c33551a4

**Comment by amanssit** [comment]
I'll do and comment, U get a mail update

**Comment by manjeshpv** [comment]
Close this

**Comment by manjeshpv** [comment]
https://github.com/amanssit/healthyapp/commit/67d173b5c021fdd3cf3a13ba221522d80933d824
