### ISSUE TITLE
output is not comming in mobile y i dont know only some text is comming from footer at top

### ISSUE THREAD

**Issue by amanssit** [amanssit/healthyapp#8]
output is not comming in mobile y i dont know only some text is comming from footer at top

**Comment by manjeshpv** [comment]
https://github.com/manjeshpv/healthyapp/commit/13a2a4d9975048358ae106bbea9006aa49f066d7

**Comment by manjeshpv** [comment]
https://plus.google.com/u/0/photos/albums/pc62ggkeci5liceipt5l90ijahg0t1sp6?pid=6203537191257969122&oid=111536767467870097902

**Comment by manjeshpv** [comment]
![2015-10-08](https://cloud.githubusercontent.com/assets/1999957/10387685/18744e44-6e81-11e5-8c7e-bea1a01ec6ae.png)
